// flow-typed signature: e4da1f1f1c321f30fa2e7e1d7d95f4e4
// flow-typed version: <<STUB>>/detect-browser_v^5.1.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detect-browser/es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detect-browser/es/index' {
  declare module.exports: $Exports<'detect-browser/es'>;
}
declare module 'detect-browser/es/index.js' {
  declare module.exports: $Exports<'detect-browser/es'>;
}
declare module 'detect-browser/index' {
  declare module.exports: $Exports<'detect-browser'>;
}
declare module 'detect-browser/index.js' {
  declare module.exports: $Exports<'detect-browser'>;
}
